#!/usr/bin/python3
""" RSA challenge that gets the first factor of a number """

import math

def get_factor(num):
    squ = int(math.sqrt(num))
    for m in range(2, squ + 1):
        if num % m == 0:
            return m
    return -1

def main(file_name):
    """ we open the file first, read in its contents and find the factors """

    try:
        with open(file_name, 'r') as file:
            for line in file:
                num = int(line.strip())
                get_num = get_factor(num)
                if get_num != -1:
                    fac = num // get_num
                    print(f"{num}={fac}*{get_num}")
                else:
                    print(f"No factor found for the {num}")
    except FileNotFoundError:
        print(f"can't open file {file_name}")

if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print("please include the file name")
        sys.exit(1)
    main(sys.argv[1])

